### ISSUE TITLE
skellett is not working on 1.16.4

### ISSUE THREAD

**Issue by ansh096** [TheLimeGlass/Skellett#128]
`[09:55:17 ERROR]: Error occurred while enabling Skellett v1.9.11 (Is it up to date?)
java.lang.NoClassDefFoundError: net/citizensnpcs/api/event/NPCDamageByEntityEvent
        at com.gmail.thelimeglass.Register.events(Register.java:395) ~[?:?]
        at com.gmail.thelimeglass.Skellett.onEnable(Skellett.java:199) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-778]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-778]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-778]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-778]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-778]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594) ~[patched_1.16.5.jar:git-Paper-778]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-778]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069) ~[patched_1.16.5.jar:git-Paper-778]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-778]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: net.citizensnpcs.api.event.NPCDamageByEntityEvent
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:155) ~[patched_1.16.5.jar:git-Paper-778]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Paper-778]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        ... 12 more`

i got this error please help how do i fix it

**Comment by TheLimeGlass** [comment]
You are using a Citizens NPC event but you don't have the setting enabled in the configuration of Skellett. Make sure that's on.

Please provide your Citizens version.

**Comment by TheLimeGlass** [comment]
Duplicate and fixed in 2.0.4 https://github.com/TheLimeGlass/Skellett/issues/167
