### ISSUE TITLE
Skellett not work

### ISSUE THREAD

**Issue by loolkkekrr** [TheLimeGlass/Skellett#184]
Skellett v2.0.1-2.0.2 not want work with 2.6.1 version skript (Java 11)
Skellett v2.0.3-2.0.7 not want work with 2.6.1 and last version skript (Java 17)
Minecraft version: 1.12.2 Spigot
Latest skellett not supported java 8-16
LOGS
Skellett version 2.0.7
```
[14:06:51 INFO]: [Skellett] Enabling Skellett v2.0.7
[14:06:51 INFO]: [Skellett] config.yml not found, generating a new config!
[14:06:51 INFO]: [Skellett] CustomEvents.yml not found, generating a new config!
[14:06:51 INFO]: [Skellett] Syntax.yml not found, generating a new file!
[14:06:51 INFO]: [Skellett] SyntaxToggles.yml not found, generating a new file!
[14:06:51 ERROR]: Error occurred while enabling Skellett v2.0.7 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/block/data/BlockData
        at me.limeglass.skellett.elements.DefaultConverters.<clinit>(DefaultConverters.java:14) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:107) ~[?:?]
        at com.gmail.thelimeglass.Skellett.onEnable(Skellett.java:177) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1620]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.block.data.BlockData
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:109) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.12.2.jar:git-Paper-1620]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 16 more
[14:06:51 INFO]: [Skellett] Disabling Skellett v2.0.7
```
Skellett version 2.0.3
```
[13:54:08 INFO]: [Skellett] Enabling Skellett 2.0.3
[13:54:08 INFO]: [Skellett] config.yml not found, generating a new config!
[13:54:08 INFO]: [Skellett] CustomEvents.yml not found, generating a new config!
[13:54:08 INFO]: [Skellett] Syntax.yml not found, generating a new file!
[13:54:08 INFO]: [Skellett] SyntaxToggles.yml not found, generating a new file!
[13:54:08 ERROR]: Error occurred while enabling Skellett v2.0.3 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/block/data/BlockData
        at me.limeglass.skellett.elements.DefaultConverters.<clinit>(DefaultConverters.java:14) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:107) ~[?:?]
        at com.gmail.thelimeglass.Skellett.onEnable(Skellett.java:195) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1620]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.block.data.BlockData
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:109) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.12.2.jar:git-Paper-1620]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 16 more
[13:54:08 INFO]: [Skellett] Disabling Skellett 2.0.3
```
Skellett version 2.0.2
```
[14:19:46 INFO]: [Skellett] Enabling Skellett v2.0.2
[14:19:46 INFO]: [Skellett] config.yml not found, generating a new config!
[14:19:46 INFO]: [Skellett] CustomEvents.yml not found, generating a new config!
[14:19:46 INFO]: [Skellett] Syntax.yml not found, generating a new file!
[14:19:46 INFO]: [Skellett] SyntaxToggles.yml not found, generating a new file!
[14:19:46 ERROR]: Error occurred while enabling Skellett v2.0.2 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/block/data/BlockData
        at me.limeglass.skellett.elements.DefaultConverters.<clinit>(DefaultConverters.java:14) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:466) ~[?:?]
        at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:107) ~[?:?]
        at com.gmail.thelimeglass.Skellett.onEnable(Skellett.java:195) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1620]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.block.data.BlockData
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:109) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.12.2.jar:git-Paper-1620]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        ... 16 more
[14:19:46 INFO]: [Skellett] Disabling Skellett v2.0.2
```

**Comment by TheLimeGlass** [comment]
Use 2.0.7 it fixed this already
